#!/bin/bash

[ -z "$1" ] && echo "usage: ./build <directory>" && echo "e.g. ./build disass" && exit 1

# read .env
if [ -f .env ]
then
  export $(cat .env | sed 's/#.*//g' | xargs)
fi

[ -z "$JAVA_PATH" ] && JAVA_PATH=java
[ -z "$APKTOOL_PATH" ] && APKTOOL_PATH=/opt/bttv/apktool_2.5.0.jar
[ -z "$UBER_APK_SIGNER_PATH" ] && UBER_APK_SIGNER_PATH=/opt/bttv/uber-apk-signer-1.2.1.jar

echo "JAVA_PATH: $JAVA_PATH"
echo "APKTOOL_PATH: $APKTOOL_PATH"
echo "UBER_APK_SIGNER_PATH: $UBER_APK_SIGNER_PATH"

# Set version
VERSION=$(jq -r ".version" bttv.manifest.json)
VERSIONCODE=$(jq -r ".versionCode" bttv.manifest.json)
sed -i "s/android:versionCode=\".*\"/android:versionCode=\"${VERSIONCODE}\"/" $1/AndroidManifest.xml
sed -i "s/android:versionName=\".*\"/android:versionName=\"${VERSION}\"/" $1/AndroidManifest.xml
sed -i "s/android:text=\"BTTV .*\"/android:text=\"BTTV ${VERSION}\"/" $1/res/layout/settings_logout_footer.xml

cd $1

# Move classes2 to classes9
echo "Moving classes2 to classes9"
mkdir -p smali_classes9/com/amazon

mv smali_classes2/com/amazon smali_classes9/com

APK_PATH=./dist/twitch.apk

# Build using APKTool
$JAVA_PATH -Xmx6g -jar $APKTOOL_PATH b . --use-aapt2 &&

# Sign with keystore if available, else use debug KS
if [ -z "$KS" ]; then

	$JAVA_PATH -jar $UBER_APK_SIGNER_PATH -a $APK_PATH
	rm $APK_PATH &&
	mv ./dist/twitch-aligned-debugSigned.apk $APK_PATH
else
	$JAVA_PATH -jar $UBER_APK_SIGNER_PATH -a $APK_PATH --ks $KS --ksAlias bttv-android --ksPass $KSPASS --ksKeyPass $KSPASS
	rm $APK_PATH &&
	mv ./dist/twitch-aligned-signed.apk $APK_PATH
fi

echo "Done: $APK_PATH"

