#!/bin/bash

[ -z "$JAVA_PATH" ] && JAVA_PATH=java
[ -z "$JAVAC_PATH" ] && JAVAC_PATH=javac
[ -z "$BUILDTOOLS_PATH" ] && BUILDTOOLS_PATH=~/Android/Sdk/build-tools/30.0.3
[ -z "$BAKSMALI_PATH" ] && BAKSMALI_PATH=/opt/baksmali/baksmali-2.4.0.jar
[ -z "$TARGETDIR" ] && TARGETDIR=extracted

echo "JAVA_PATH: $JAVA_PATH"
echo "JAVAC_PATH: $JAVAC_PATH"
echo "BAKSMALI_PATH: $BAKSMALI_PATH"
echo "TARGETDIR: $TARGETDIR"
echo "BUILDTOOLS_PATH: $BUILDTOOLS_PATH"

DX=$BUILDTOOLS_PATH/dx
OUTDIR=sourceout
$JAVAC_PATH -cp source -d $OUTDIR -source 1.7 -target 1.7 source/bttv/*.java &&
cd $OUTDIR

for file in bttv/*.class; do
  echo $file
  $DX --dex --output ${file/.class/.dex} $file
done
for file in bttv/*.dex; do
  echo $file
  $JAVA_PATH -jar $BAKSMALI_PATH d -o . $file
done

mkdir -p ../$TARGETDIR/smali_classes10/bttv

for file in bttv/*.smali; do
  echo $file
  cp $file ../$TARGETDIR/smali_classes10/$file
done
