#!/bin/bash

[ -z "$JAVA_PATH" ] && JAVA_PATH=java
[ -z "$JAVAC_PATH" ] && JAVAC_PATH=javac
[ -z "$ANDROID_SDK_ROOT" ] && ANDROID_SDK_ROOT=~/Android/Sdk
[ -z "$BAKSMALI_PATH" ] && BAKSMALI_PATH=/opt/baksmali/baksmali-2.4.0.jar
[ -z "$1" ] && TARGETDIR=extracted || TARGETDIR=$1
[ -z "$BUILD_COMPANION" ] && BUILD_COMPANION=/opt/build-companion


echo "JAVA_PATH: $JAVA_PATH"
echo "JAVAC_PATH: $JAVAC_PATH"
echo "BAKSMALI_PATH: $BAKSMALI_PATH"
echo "TARGETDIR: $TARGETDIR"
echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
echo "BUILD_COMPANION: $BUILD_COMPANION"

export ANDROID_SDK_ROOT

# find dx tool
DX_PATTERN="$ANDROID_SDK_ROOT/build-tools/*/dx"
DX_FILES=( $DX_PATTERN )
DX=${DX_FILES[0]}
echo "$DX"

# build mod
cd mod
bash gradlew build

# fail if failed
[ $? = 0 ] || exit 1

# contants
CONSUMER_APK=consumer/build/outputs/apk/release/consumer-release-unsigned.apk
CONSUMER_TMP=consumer/build/.bttv_tmp
CONSUMER_DEX="$CONSUMER_TMP/classes.dex"

AAR_FILE=app/build/outputs/aar/app-debug.aar
TMP_DIR=app/build/.bttv_tmp
JAR_FILE="$TMP_DIR/classes.jar"
DEX_FILE="$TMP_DIR/bttv.dex"
FINAL_TARGET="../$TARGETDIR/smali_classes7"
RES_DIR="app/src/main/res"
RES_TARGET="../$TARGETDIR/res"
LIB_DIR="$TMP_DIR/jni"
LIB_TARGET="../$TARGETDIR/lib"

# extract classes
unzip -o "$AAR_FILE" "classes.jar" "jni/**/*" -d "$TMP_DIR"
unzip -o "$CONSUMER_APK" "classes.dex" -d "$CONSUMER_TMP"

# dex classes.jar
$DX --dex --output "$DEX_FILE" "$JAR_FILE"

# baksmali .dex file
$JAVA_PATH -jar $BAKSMALI_PATH d -o "$TMP_DIR" "$DEX_FILE"
$JAVA_PATH -jar $BAKSMALI_PATH d -o "$CONSUMER_TMP" "$CONSUMER_DEX"

# replace BTTVDefaultConstructorMarker with DefaultConstructorMarker
find "$TMP_DIR/bttv" -type f -exec sed -i -e 's/BTTVDefaultConstructorMarker/DefaultConstructorMarker/g' {} \;

# remove dir if already exists
mkdir -p "$FINAL_TARGET/bttv"
rm -rf "$FINAL_TARGET/bttv"
rm -rf "$FINAL_TARGET/com"

# move to target
mv "$TMP_DIR/bttv" "$FINAL_TARGET/."
mv "$TMP_DIR/com" "$FINAL_TARGET/."

rsync -ar --ignore-existing "$CONSUMER_TMP/androidx/" "../$TARGETDIR/smali_classes8/androidx/"

# copy res
ls "$RES_DIR" -1 | grep -v values | xargs -i cp -R "$RES_DIR/{}" "$RES_TARGET"
ls "$LIB_DIR" -1 | xargs -i cp -r "$LIB_DIR/{}" "$LIB_TARGET"

# add strings
$BUILD_COMPANION strings "$RES_DIR" "$RES_TARGET"

# remove temp dir
rm -rf "$TMP_DIR" # "$CONSUMER_TMP"

