#!/bin/bash

[ -z "$JAVA_PATH" ] && JAVA_PATH=java
[ -z "$APKTOOL_PATH" ] && APKTOOL_PATH=/opt/apktool/apktool.jar
[ -z "$ZIP_FILE" ] && ZIP_FILE=twitch.zip
[ -z "$PUBLIC_FIXER" ] && PUBLIC_FIXER=/opt/public-fixer
[ -z "$UBER_APK_SIGNER_PATH" ] && UBER_APK_SIGNER_PATH=/opt/uber-apk-signer/uber-apk-signer-1.2.1.jar

echo "JAVA_PATH: $JAVA_PATH"
echo "APKTOOL_PATH: $APKTOOL_PATH"
echo "ZIP_FILE: $ZIP_FILE"
echo "PUBLIC_FIXER: $PUBLIC_FIXER"
echo "UBER_APK_SIGNER_PATH: $UBER_APK_SIGNER_PATH"

# Unzip to .tmp
rm -rf .tmp &&
unzip $ZIP_FILE -d .tmp

#
# Verify integrity
#

# compare with https://twitch.tv/.well-known/assetlinks.json
FMT_TWITCH_SHA="13:38:F9:B0:49:89:3C:C7:0B:78:43:2A:17:75:82:F9:0B:D4:BC:62:96:EA:4E:D3:5B:CC:7D:F5:96:87:AC:53"
TWITCH_SHA=$(echo $FMT_TWITCH_SHA | sed 's/\://g') # remove all ':'

echo "~~~ Print signatures ~~~" &&
$JAVA_PATH -jar $UBER_APK_SIGNER_PATH -y --verifySha256 $TWITCH_SHA -a .tmp/*.apk

# exit if verification failed
[ $? -eq 2 ] &&
echo "ERROR: 
ERROR: One or more apk files where not signed by twitch!
ERROR: This most likely means you have downloaded a potentialy malicious zip archive!
ERROR: " &&
exit 1

#
# disassemble apk files
#

for file in .tmp/*.apk; do
  echo $file
  echo ====
  $JAVA_PATH -Xmx256m -jar $APKTOOL_PATH d $file -o .tmp/disass/${file/.tmp\//} $file
done

mv .tmp/disass/tv.twitch.android.app.apk .tmp/base
find .tmp/base | sed "s/.tmp\/base//" > .tmp/pre.txt

#
# copy all files to base (don't overwrite)
#
for dir in .tmp/disass/*; do
  cp -r -n $dir/* .tmp/base
done

find .tmp/base | sed "s/.tmp\/base//" > .tmp/post.txt
diff -u .tmp/pre.txt .tmp/post.txt | grep -E "^\+" > .tmp/additions.txt

# fix public.xml
$PUBLIC_FIXER .tmp/base .tmp/disass/*/res/values/public.xml

# remove android:isSplitRequired="true"
sed -i 's/android:isSplitRequired="true"//' .tmp/base/AndroidManifest.xml

# rename apk
sed -i "s/apkFileName: tv.twitch.android.app.apk/apkFileName: twitch.apk/" .tmp/base/apktool.yml

#
# clean up
#
mv .tmp/base disass
rm .tmp -rf
