#!/bin/bash

[ -z "$1" ] && echo "usage: ./genmonke <targetdir>" && echo "e.g.: ./genmonke disass" && exit 1

if ! cd $1; then
    exit 1
fi

Files=$(git diff base --name-only)

rm -rf ../patches
mkdir ../patches

for File in $Files
do
    Path=../patches/$(echo $File | sed 's/\//./g;s/smali_classes[0-9]\.//; s/smali\.//').patch
    echo $File
    git diff --minimal base $File | sed '/^index [a-zA-Z0-9]\{9\}\.\.[a-z0-9]\{9\}/d' > $Path
done
