#!/bin/bash

if ! cd disass; then
    exit 1
fi

git init
git add .

if ! cd ../patches; then
    exit 1
fi

for File in *.patch
do
    cd ../disass
    echo $File
    git apply --index ../patches/$File || exit 1
done
