name: 🐛 Bug Report
description: If something isn't working as expected.
labels:
  - "bug"
body:
  - type: checkboxes
    id: checked-existing-issues
    attributes:
      label: Existing Issues
      description: https://github.com/bttv-android/bttv/issues?q=is%3Aissue
      options:
        - label: I have searched for existing issues, this is not a duplicate.
          required: true
  - type: checkboxes
    id: checked-native-twitch
    attributes:
      label: Unmodded Twitch
      description: bttv-android does not fix bugs introduced by Twitch themselves
      options:
        - label: I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App
          required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: bttv-version
    attributes:
      label: bttv-android version
      description: You find this in the App's settings below the Twitch version code
      placeholder: e.g. v0.27.0-beta
    validations:
      required: false
  - type: input
    id: android-version
    attributes:
      label: android version
      placeholder: e.g. Oreo, 11, ...
    validations:
      required: false
  - type: input
    id: device
    attributes:
      label: device
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
